### Numpy

In [7]:
import numpy as np

In [8]:
np.random.randint(0, 10 )

6

### tasks

In [10]:
from MFEA_lib.tasks import Benchmark

In [11]:
cec17 = Benchmark.CEC17_benchmark.get_10tasks_benchmark()

In [12]:
for t in cec17:
    print(t.name)

Sphere: [-100, 100]^50
Sphere: [-100, 100]^50
Sphere: [-100, 100]^50
Weierstrass: [-0.5, 0.5]^25
Rosenbrock: [-50, 50]^50
Ackley: [-50, 50]^50
Weierstrass: [-0.5, 0.5]^50
Schwefel: [-500, 500]^50
Griewank: [-100, 100]^50
Rastrigin: [-50, 50]^50


In [13]:
for t in cec17:
    print(t.global_optimal[[0, -1]])

[0. 0.]
[80. 80.]
[-80. -80.]
[-0.4 -0.4]
[0. 0.]
[40. 40.]
[-0.4 -0.4]
[420.9687 420.9687]
[-80.  80.]
[ 40. -40.]


In [14]:
print(cec17[0].encode(cec17[0].global_optimal)[[0, -1]])
print(cec17[1].encode(cec17[1].global_optimal)[[0, -1]])
print(cec17[2].encode(cec17[2].global_optimal)[[0, -1]])
print(cec17[3].encode(cec17[3].global_optimal)[[0, -1]])
print(cec17[4].encode(cec17[4].global_optimal)[[0, -1]])
print(cec17[5].encode(cec17[5].global_optimal)[[0, -1]])
print(cec17[6].encode(cec17[6].global_optimal)[[0, -1]])
print(cec17[7].encode(cec17[7].global_optimal)[[0, -1]])
print(cec17[8].encode(cec17[8].global_optimal)[[0, -1]])
print(cec17[9].encode(cec17[9].global_optimal)[[0, -1]])

[0.5 0.5]
[0.9 0.9]
[0.1 0.1]
[0.1 0.1]
[0.5 0.5]
[0.9 0.9]
[0.1 0.1]
[0.9209687 0.9209687]
[0.1 0.9]
[0.9 0.1]


shift

encode: đầu vào là không gian đã dịch chuyển

> R' -bound-> bounded_space -encode-> [0, 1] 

decode: đầu vào là không gian mã hóa [0, 1] 

>[0, 1] -decode-> bounded_space -unbound-> R' -inv_shift-> R

In [15]:
cec17_2 = Benchmark.CEC17_benchmark.get_10tasks_benchmark()

In [16]:
cec17[0]

In [17]:
cec17_2[0]

In [18]:
cec17[0] == cec17_2[0]

True

### EA

In [19]:
from MFEA_lib.EA import *


#### Population

In [22]:
popTest = Population(
    nb_inds_tasks= [2] * 10,
    dim = 50,
    list_tasks= cec17
)
popTest

In [23]:
popTest2 = Population(
    nb_inds_tasks= [2] * 10,
    dim = 50,
    list_tasks= cec17
)
popTest2

In [24]:
c = popTest + popTest2
c

In [25]:
print(len(popTest))
print(len(popTest2))
print(len(c))

20
20
40


In [26]:
popTest[0][:]

[Genes: [0.46164388 0.4233285  0.15626752 0.10088391 0.34386453 0.883532
  0.91643783 0.98939309 0.67612092 0.86075783 0.69916641 0.30496891
  0.90777943 0.04126623 0.08865193 0.14026841 0.84213221 0.10838536
  0.0162905  0.97365559 0.84315394 0.40077341 0.40248284 0.29409224
  0.52089961 0.10015175 0.54370364 0.33961805 0.80301407 0.46437637
  0.76998749 0.54764848 0.47067857 0.42219737 0.13279903 0.58361346
  0.45423458 0.13099108 0.16581432 0.04894305 0.79829997 0.80810743
  0.46785061 0.3088698  0.0376774  0.45691843 0.47960675 0.56820026
  0.3744309  0.53690643]
 Skill_factor: 0,
 Genes: [0.49649856 0.94896016 0.10053351 0.8745096  0.77695419 0.71690982
  0.87229593 0.97274713 0.61008705 0.21876374 0.81221339 0.82854541
  0.76608651 0.87496613 0.51419978 0.62629969 0.56354888 0.20626146
  0.6806801  0.51204525 0.22777653 0.7505083  0.908414   0.57727797
  0.64500728 0.2765501  0.67606173 0.14076511 0.22838142 0.593462
  0.93685208 0.18751955 0.08293849 0.31001825 0.21065664 0.6690

In [27]:
popTest2[0][:]

[Genes: [0.88304075 0.72118891 0.0201793  0.33457004 0.5157941  0.50147531
  0.57107768 0.5250045  0.34233346 0.72414905 0.32732629 0.70784553
  0.53550391 0.93327977 0.71889439 0.66404577 0.34238786 0.62890143
  0.74445123 0.18748554 0.56657829 0.28616557 0.67610112 0.51806145
  0.1402275  0.99493701 0.42748876 0.96233551 0.58104136 0.14206817
  0.03854541 0.32691702 0.82579177 0.58696512 0.9339228  0.6532305
  0.61156161 0.66141699 0.35337829 0.22569185 0.25692658 0.47236967
  0.82568799 0.44412585 0.48186248 0.78923157 0.97877723 0.56867029
  0.66850105 0.54190978]
 Skill_factor: 0,
 Genes: [0.51665764 0.47942246 0.53084904 0.76311166 0.57545277 0.04650171
  0.32070061 0.94695423 0.48509906 0.48221233 0.40028273 0.35147231
  0.00549157 0.40697814 0.49657332 0.17055318 0.32934944 0.42264827
  0.57836944 0.2379168  0.63564814 0.55353636 0.12854876 0.0118892
  0.64335335 0.61509198 0.46225148 0.41600444 0.36226378 0.34941808
  0.76721366 0.20967328 0.49495236 0.7866543  0.8532377  0.00

In [28]:
c[0][:]

[Genes: [0.46164388 0.4233285  0.15626752 0.10088391 0.34386453 0.883532
  0.91643783 0.98939309 0.67612092 0.86075783 0.69916641 0.30496891
  0.90777943 0.04126623 0.08865193 0.14026841 0.84213221 0.10838536
  0.0162905  0.97365559 0.84315394 0.40077341 0.40248284 0.29409224
  0.52089961 0.10015175 0.54370364 0.33961805 0.80301407 0.46437637
  0.76998749 0.54764848 0.47067857 0.42219737 0.13279903 0.58361346
  0.45423458 0.13099108 0.16581432 0.04894305 0.79829997 0.80810743
  0.46785061 0.3088698  0.0376774  0.45691843 0.47960675 0.56820026
  0.3744309  0.53690643]
 Skill_factor: 0,
 Genes: [0.49649856 0.94896016 0.10053351 0.8745096  0.77695419 0.71690982
  0.87229593 0.97274713 0.61008705 0.21876374 0.81221339 0.82854541
  0.76608651 0.87496613 0.51419978 0.62629969 0.56354888 0.20626146
  0.6806801  0.51204525 0.22777653 0.7505083  0.908414   0.57727797
  0.64500728 0.2765501  0.67606173 0.14076511 0.22838142 0.593462
  0.93685208 0.18751955 0.08293849 0.31001825 0.21065664 0.6690

#### SubPop

In [29]:
subPopTest = SubPopulation(
    skill_factor= 0,
    num_inds= 100,
    dim= 50,
    task= cec17[0]
)
subPopTest

In [30]:
i = 0
subPopTest1 = SubPopulation(
    skill_factor= i,
    num_inds= 100,
    dim= 50,
    task= cec17[i]
)
subPopTest1

In [57]:
subPopTest[[1, 3]]

[Genes: [0.22533535 0.98891094 0.1094353  0.99034782 0.74593529 0.32694738
  0.31522273 0.16777412 0.18530104 0.96411764 0.04891095 0.66698934
  0.79471279 0.00891547 0.87394663 0.8472241  0.05137865 0.18442521
  0.92696334 0.61720126 0.61905856 0.2637743  0.99924342 0.43148601
  0.15820867 0.19747656 0.77535334 0.95890901 0.160858   0.18156014
  0.95318747 0.37983784 0.68181932 0.04704641 0.71162838 0.67659418
  0.22707309 0.13762696 0.11230039 0.82527951 0.69041907 0.24497875
  0.02081771 0.49654937 0.74121183 0.44350789 0.45625071 0.03304129
  0.50507345 0.22817926]
 Skill_factor: 0,
 Genes: [0.14077728 0.5395544  0.32708139 0.82513411 0.10301645 0.73478529
  0.20750692 0.26462456 0.79700345 0.60303914 0.36327138 0.1605649
  0.61798407 0.05023258 0.06034031 0.52369437 0.16272844 0.30460514
  0.04260747 0.60452004 0.38287916 0.52599195 0.40634304 0.51464624
  0.15895625 0.98670621 0.98338898 0.73888049 0.75326246 0.18511355
  0.48764426 0.14486925 0.03258252 0.75294723 0.63443601 0.5

In [31]:
c = subPopTest + subPopTest1
c

In [32]:
len(c)

200

In [33]:
a = subPopTest.ls_inds

In [34]:
c.factorial_rank

array([ 76, 197, 172,  99, 186, 125,   7,  68, 170,  10,  59, 196, 161,
       167, 109,  78, 141,  97, 180, 113, 159, 138, 142, 140, 145,  50,
        72,  17,  39,  55,  30,  44, 102, 164, 158,  12,  54,   6,  87,
       122, 124,  88, 104,  67,   8, 137,  79,  82,  58, 189, 143,  73,
       133, 168,  25, 123,  77,  74, 176,  23, 194,  34,  32, 162,  46,
       175, 193, 155,  70, 178, 107, 200,  69,  65,  28,  64, 149,  71,
       198, 110, 139, 112, 187, 100,  84,  16,  53,  11,  38, 184,  27,
        96, 128,  52,  47, 132, 157,  98, 144, 165,  93, 127,  89, 152,
       153,   2, 188,  18, 154,  80, 135,   3,  86,  37, 116,  57,   9,
       114, 174, 151,  63, 156,  62, 182,  42, 183,  14, 199, 169,  66,
         5,  26, 121,   1,  45, 148,  21,  29,  15,  56, 179, 163, 105,
       195,  24, 171, 146,  94,  91,  51,  90,  13, 117, 185, 190, 177,
       118,  36,  49, 120, 130,  95, 160,  41,  31, 108, 106, 134,   4,
        22, 173,  19,  81,  33, 147, 191, 111,  20,  48,  83, 10

#### Individual

In [35]:
a = Individual(np.arange(10))
a.skill_factor = 0
a.fcost = 1

In [36]:
b = Individual(np.arange(10, 20))
b.skill_factor = 1
b.fcost = 0.5

In [37]:
c = Individual(np.arange(5, 15))
c.skill_factor  = 0
c.fcost = 0.1

In [38]:
a

Genes: [0 1 2 3 4 5 6 7 8 9]
Skill_factor: 0

In [39]:
b

Genes: [10 11 12 13 14 15 16 17 18 19]
Skill_factor: 1

In [40]:
c

Genes: [ 5  6  7  8  9 10 11 12 13 14]
Skill_factor: 0

In [41]:
a + b

Genes: [10 12 14 16 18 20 22 24 26 28]
Skill_factor: 0

In [42]:
a - b

Genes: [-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]
Skill_factor: 0

In [43]:
a * b

Genes: [  0  11  24  39  56  75  96 119 144 171]
Skill_factor: 0

In [44]:
a / b

Genes: [0.         0.09090909 0.16666667 0.23076923 0.28571429 0.33333333
 0.375      0.41176471 0.44444444 0.47368421]
Skill_factor: 0

In [45]:
a // b

Genes: [0 0 0 0 0 0 0 0 0 0]
Skill_factor: 0

In [46]:
a % b

Genes: [0 1 2 3 4 5 6 7 8 9]
Skill_factor: 0

In [47]:
a ** b

Genes: [                  0                   1                4096
             1594323           268435456         30517578125
       2821109907456     232630513987207   18014398509481984
 1350851717672992089]
Skill_factor: 0

In [48]:
a < b

False

In [49]:
a < c

True

In [50]:
idx = np.random.choice(10, 3)
idx

array([7, 8, 5])

In [51]:
a

Genes: [0 1 2 3 4 5 6 7 8 9]
Skill_factor: 0

In [52]:
b

Genes: [10 11 12 13 14 15 16 17 18 19]
Skill_factor: 1

In [53]:
a[idx]

array([7, 8, 5])

In [54]:
b[idx]

array([17, 18, 15])

In [55]:
a[idx] = b[idx]

TypeError: only integer scalar arrays can be converted to a scalar index

In [ ]:
a.genes[idx] = b.genes[idx]

In [ ]:
a

Genes: [10  1  2  3  4  5  6  7 18 19]
Skill_factor: 0