In [94]:
import time

In [95]:
import numpy as np

In [96]:
np.random.randint(0, 10 )

1

### tasks

In [97]:
from MFEA_lib.tasks import Benchmark

In [98]:
cec17 = Benchmark.CEC17_benchmark.get_10tasks_benchmark()

In [99]:
for t in cec17:
    print(t.name)

Sphere: [-100, 100]^50
Sphere: [-100, 100]^50
Sphere: [-100, 100]^50
Weierstrass: [-0.5, 0.5]^25
Rosenbrock: [-50, 50]^50
Ackley: [-50, 50]^50
Weierstrass: [-0.5, 0.5]^50
Schwefel: [-500, 500]^50
Griewank: [-100, 100]^50
Rastrigin: [-50, 50]^50


In [100]:
for t in cec17:
    print(t.global_optimal[[0, -1]])

[0. 0.]
[80. 80.]
[-80. -80.]
[-0.4 -0.4]
[0. 0.]
[40. 40.]
[-0.4 -0.4]
[420.9687 420.9687]
[-80.  80.]
[ 40. -40.]


In [101]:
print(cec17[0].encode(cec17[0].global_optimal)[[0, -1]])
print(cec17[1].encode(cec17[1].global_optimal)[[0, -1]])
print(cec17[2].encode(cec17[2].global_optimal)[[0, -1]])
print(cec17[3].encode(cec17[3].global_optimal)[[0, -1]])
print(cec17[4].encode(cec17[4].global_optimal)[[0, -1]])
print(cec17[5].encode(cec17[5].global_optimal)[[0, -1]])
print(cec17[6].encode(cec17[6].global_optimal)[[0, -1]])
print(cec17[7].encode(cec17[7].global_optimal)[[0, -1]])
print(cec17[8].encode(cec17[8].global_optimal)[[0, -1]])
print(cec17[9].encode(cec17[9].global_optimal)[[0, -1]])

[0.5 0.5]
[0.9 0.9]
[0.1 0.1]
[0.1 0.1]
[0.5 0.5]
[0.9 0.9]
[0.1 0.1]
[0.9209687 0.9209687]
[0.1 0.9]
[0.9 0.1]


shift

encode: đầu vào là không gian đã dịch chuyển

> R' -bound-> bounded_space -encode-> [0, 1] 

decode: đầu vào là không gian mã hóa [0, 1] 

>[0, 1] -decode-> bounded_space -unbound-> R' -inv_shift-> R

In [102]:
cec17_2 = Benchmark.CEC17_benchmark.get_10tasks_benchmark()

In [103]:
cec17[0]

In [104]:
cec17_2[0]

In [105]:
cec17[0] == cec17_2[0]

True

In [106]:
a = time.time()
for i in range(10000):
    cec17[0] == cec17_2[0]
time.time() - a

0.055269479751586914

In [107]:
a = time.time()
for i in range(10000):
    cec17[0] == cec17[0]
time.time() - a

0.009485244750976562

### EA

In [108]:
from MFEA_lib.EA import *


#### Population

In [109]:
popTest = Population(
    num_inds_tasks= [2] * 10,
    dim = 50,
    list_tasks= cec17
)
popTest

In [110]:
popTest2 = Population(
    num_inds_tasks= [2] * 10,
    dim = 50,
    list_tasks= cec17
)
popTest2

In [111]:
c = popTest + popTest2
c

In [112]:
print(len(popTest))
print(len(popTest2))
print(len(c))

20
20
40


In [113]:
popTest[0][:]

[Genes: [0.41418209 0.03937598 0.41647873 0.90576682 0.77883933 0.16519674
  0.52007358 0.61893286 0.17962291 0.47221915 0.62526914 0.33889539
  0.86502686 0.80111413 0.72580267 0.03988543 0.31533665 0.9856574
  0.0988608  0.66272625 0.50709804 0.40588161 0.32723217 0.26946509
  0.33743995 0.59906049 0.45927618 0.67467029 0.83790194 0.12901333
  0.92347082 0.98386155 0.71228343 0.72259621 0.96866726 0.42352799
  0.04911001 0.48104873 0.35282102 0.34430987 0.69694298 0.8294831
  0.5932291  0.53516399 0.47999502 0.2212561  0.87487185 0.0714026
  0.61412782 0.32586342]
 Skill_factor: 0,
 Genes: [0.40074625 0.69250141 0.09824934 0.2355427  0.66031199 0.10838882
  0.48730147 0.11157017 0.46087129 0.04181642 0.90107095 0.80686989
  0.17562133 0.42614728 0.60669317 0.62272897 0.33081023 0.23713218
  0.1899036  0.56377351 0.93143689 0.74417486 0.24521821 0.63316821
  0.93115456 0.42954876 0.55320537 0.93248867 0.23118499 0.16878755
  0.44263788 0.73375524 0.44686301 0.27083053 0.73458997 0.682

In [114]:
popTest2[0][:]

[Genes: [0.24414185 0.76918178 0.33222282 0.64947108 0.77492162 0.32737485
  0.52169348 0.71168416 0.35722938 0.57252534 0.67749411 0.59118769
  0.22480831 0.32120046 0.45796041 0.93829362 0.27581043 0.58624278
  0.92269544 0.54984034 0.04558765 0.33472943 0.63937944 0.78260755
  0.32709283 0.59164707 0.0047156  0.13824346 0.5230024  0.56224126
  0.34745125 0.71938834 0.91431283 0.57832715 0.61270037 0.96051134
  0.80755801 0.77731701 0.27917635 0.35961197 0.35129605 0.69374477
  0.62718079 0.10992665 0.20959712 0.78059797 0.74782608 0.04475093
  0.94204823 0.25635102]
 Skill_factor: 0,
 Genes: [0.12296975 0.22748151 0.81595396 0.67438079 0.42867252 0.36152873
  0.59826127 0.20258112 0.97867637 0.87387796 0.95615444 0.59093436
  0.07011999 0.54340301 0.12190255 0.94367093 0.7484525  0.1118111
  0.94522715 0.42196034 0.97237449 0.10257745 0.95294937 0.24083269
  0.10014066 0.73718474 0.17208158 0.52972778 0.36423724 0.91730281
  0.93038248 0.64800951 0.26026255 0.24843541 0.09569111 0.4

In [115]:
c[0][:]

[Genes: [0.41418209 0.03937598 0.41647873 0.90576682 0.77883933 0.16519674
  0.52007358 0.61893286 0.17962291 0.47221915 0.62526914 0.33889539
  0.86502686 0.80111413 0.72580267 0.03988543 0.31533665 0.9856574
  0.0988608  0.66272625 0.50709804 0.40588161 0.32723217 0.26946509
  0.33743995 0.59906049 0.45927618 0.67467029 0.83790194 0.12901333
  0.92347082 0.98386155 0.71228343 0.72259621 0.96866726 0.42352799
  0.04911001 0.48104873 0.35282102 0.34430987 0.69694298 0.8294831
  0.5932291  0.53516399 0.47999502 0.2212561  0.87487185 0.0714026
  0.61412782 0.32586342]
 Skill_factor: 0,
 Genes: [0.40074625 0.69250141 0.09824934 0.2355427  0.66031199 0.10838882
  0.48730147 0.11157017 0.46087129 0.04181642 0.90107095 0.80686989
  0.17562133 0.42614728 0.60669317 0.62272897 0.33081023 0.23713218
  0.1899036  0.56377351 0.93143689 0.74417486 0.24521821 0.63316821
  0.93115456 0.42954876 0.55320537 0.93248867 0.23118499 0.16878755
  0.44263788 0.73375524 0.44686301 0.27083053 0.73458997 0.682

#### SubPop

In [116]:
subPopTest = SubPopulation(
    skill_factor= 0,
    num_inds= 100,
    dim= 50,
    task= cec17[0]
)
subPopTest

In [117]:
i = 0
subPopTest1 = SubPopulation(
    skill_factor= i,
    num_inds= 100,
    dim= 50,
    task= cec17[i]
)
subPopTest1

In [118]:
c = subPopTest + subPopTest1
c

In [119]:
len(c)

200

In [142]:
a = subPopTest.ls_inds

In [120]:
c.factorial_rank

array([143, 195, 176,  52, 154, 109,  17,  62, 113,  35,  10, 187, 127,
       198, 128,  49,  34,  28,  50, 119,  46, 179, 155,  99,  40,   1,
        69,  25, 139, 124,  83, 173, 170, 189,  31,  58, 136,  37, 191,
       135,  41, 182, 175, 178,  70, 197, 105, 131,  77,  64, 165,  74,
       123, 171,   9, 159, 183,  14,  63,  42,  96,   4, 122, 180,  18,
        60,  93, 111,  39,  92, 138, 115, 188, 153, 103,  43,  87, 102,
        12, 169, 106,  15, 181,  95,  80,  73, 160,  48, 161,  68,  79,
       164,  45, 114, 172,  59,  13, 200,  29,  27,  23,  26, 151, 129,
         6, 108, 104, 148, 162,  57,   3, 134,  11, 184, 112,  91,  47,
       167,   5, 144, 146, 140, 150, 166,  88, 157, 133, 137,  94, 192,
        22,  51,   7,  71,  67,  78, 163, 101,  36, 185, 152, 125, 142,
        89,  44,  61,  30, 147, 156,  56, 193,  66, 149,  65,  84,  82,
       194,  33,  16, 120,  24,   8,  38, 177,  86,  55, 190, 132,  32,
       158,  90, 118, 174,   2,  53, 100,  81, 199, 116,  97,  7

#### Individual

In [121]:
a = Individual(np.arange(10))
a.skill_factor = 0
a.fcost = 1

In [122]:
b = Individual(np.arange(10, 20))
b.skill_factor = 1
b.fcost = 0.5

In [123]:
c = Individual(np.arange(5, 15))
c.skill_factor  = 0
c.fcost = 0.1

In [124]:
a

Genes: [0 1 2 3 4 5 6 7 8 9]
Skill_factor: 0

In [125]:
b

Genes: [10 11 12 13 14 15 16 17 18 19]
Skill_factor: 1

In [126]:
c

Genes: [ 5  6  7  8  9 10 11 12 13 14]
Skill_factor: 0

In [127]:
a + b

Genes: [10 12 14 16 18 20 22 24 26 28]
Skill_factor: 0

In [128]:
a - b

Genes: [-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]
Skill_factor: 0

In [129]:
a * b

Genes: [  0  11  24  39  56  75  96 119 144 171]
Skill_factor: 0

In [130]:
a / b

Genes: [0.         0.09090909 0.16666667 0.23076923 0.28571429 0.33333333
 0.375      0.41176471 0.44444444 0.47368421]
Skill_factor: 0

In [131]:
a // b

Genes: [0 0 0 0 0 0 0 0 0 0]
Skill_factor: 0

In [132]:
a % b

Genes: [0 1 2 3 4 5 6 7 8 9]
Skill_factor: 0

In [133]:
a ** b

Genes: [                  0                   1                4096
             1594323           268435456         30517578125
       2821109907456     232630513987207   18014398509481984
 1350851717672992089]
Skill_factor: 0

In [134]:
a < b

False

In [135]:
a < c

True

In [136]:
idx = np.random.choice(10, 3)
idx

array([3, 2, 8])

In [137]:
a

Genes: [0 1 2 3 4 5 6 7 8 9]
Skill_factor: 0

In [138]:
b

Genes: [10 11 12 13 14 15 16 17 18 19]
Skill_factor: 1

In [139]:
a[idx]

array([3, 2, 8])

In [140]:
b[idx]

array([13, 12, 18])

In [141]:
a[idx] = b[idx]

TypeError: only integer scalar arrays can be converted to a scalar index

In [ ]:
a.genes[idx] = b.genes[idx]

In [ ]:
a

Genes: [10  1  2  3  4  5  6  7 18 19]
Skill_factor: 0