In [1]:
import numpy as np 
import random
 

np.random.seed(1) 
print(np.random.get_state()[1][0])
state = np.random.get_state() 
print(np.random.rand())
print(state)
print(np.random.rand())

1
0.417022004702574
('MT19937', array([         1, 1812433254, 3713160357, 3109174145,   64984499,
       3392658084,  446538473, 2629760756, 2453345558, 1394803949,
       1021787430, 2063496713, 1304877364, 1713639158,  889001601,
       1651239412, 1450863289,  745575081,  361057727, 2288771950,
       1463387568, 2249488362,   26637982,  204036717, 1655702041,
       1329048465, 2092351466, 1681619666, 3220660315, 1301783610,
        626286181,  294669048, 3537128440, 3259518248, 2550101273,
       1160881866,  308703547,  295714668,   35508674, 1599247281,
        376272024, 3166459937, 1852735737, 3680868867,  612352556,
       2760189833, 3816750341,  699140493, 1087846865,  394927937,
       2063539671,  645417889, 2337669049, 3773167612,  678121169,
       3006984620, 1163491294, 2559287860,  543155592, 3194181347,
       2463543297, 3875146860,  475483913, 3707568076, 3881808875,
       1264657097,  208126250, 1802809301,  367907560, 2433375693,
       2851326449, 2380707878,

In [2]:
from MFEA_lib.EA import Individual
a = [Individual(np.random.rand(30,)) for i in range(10)]
   


In [3]:
class A():
    def __init__(self, fcost = 0): 
        self.fcost = fcost 

a = [A(fcost= i + 2) for i in range(10)]
print((np.array([ind.fcost for ind in a])))

b = A(fcost= 12)
a.append(b) 
print((np.array([ind.fcost for ind in a])))


[ 2  3  4  5  6  7  8  9 10 11]
[ 2  3  4  5  6  7  8  9 10 11 12]


<h2>Population</h2>

In [4]:
class B(): 
    def __init__(self): 
        self.b  = 10 
        self.c = 10 

In [5]:
class A() : 
    def __init__(self): 
        self.ls_inds = [B() for i in range(10)]
    def __getitem__(self, index): 
        return self.ls_inds[index] 
    
    

a = A() 


In [6]:
from MFEA_lib.EA import * 
from MFEA_lib.tasks import Benchmark


In [7]:
cec17 = Benchmark.CEC17_benchmark.get_10tasks_benchmark()

In [8]:
num_inds_tasks = np.zeros(shape = (len(cec17)), dtype= int) + 10
dim = 50

pop = Population(num_inds_tasks= num_inds_tasks, dim = dim, list_tasks= cec17)


<h3> Individual </h3>

In [12]:
ind = pop[0].__getitem__([1,3])
print(ind)

(Genes: [0.25969839 0.2570693  0.63230332 0.34529746 0.79658868 0.44614623
 0.78274941 0.99047178 0.30024834 0.14300583 0.90130844 0.54155938
 0.97474037 0.6366044  0.99391302 0.5460708  0.52642593 0.1354279
 0.35570517 0.02621857 0.16039518 0.74563719 0.03039969 0.3665431
 0.86234625 0.69267772 0.69094214 0.1886368  0.44190428 0.58157741
 0.98975171 0.20390623 0.2477329  0.26217308 0.75017241 0.45697533
 0.05692944 0.50851624 0.21196016 0.79860424 0.29733138 0.02760601
 0.59343245 0.84384043 0.38101612 0.74985831 0.51114148 0.5409518
 0.95943432 0.80396089]
Skill_factor: 0, Genes: [0.9058095  0.98995518 0.71112246 0.73180041 0.9092932  0.40087373
 0.24985068 0.17343017 0.11945705 0.81261059 0.14679237 0.26429748
 0.81908918 0.31058725 0.98241745 0.2666387  0.53365334 0.31446701
 0.91077283 0.36655664 0.43359233 0.51229269 0.93888648 0.03094901
 0.71687866 0.89101895 0.02728722 0.52205125 0.32598981 0.85948932
 0.55851655 0.69022787 0.4528535  0.62830904 0.29009685 0.00934858
 0.576755

In [ ]:
pop[0][1]

Genes: [2.26327137e-01 5.04979512e-01 9.72921206e-01 9.28352981e-01
 9.76543714e-02 9.81451420e-01 8.27242980e-01 2.03547167e-02
 4.02613306e-01 6.55729488e-01 1.70678968e-01 8.51181194e-01
 3.34421991e-01 6.09722391e-01 4.20971009e-01 8.80502928e-01
 7.48978980e-01 1.74515127e-01 1.13083516e-01 6.49064458e-01
 5.43922603e-01 1.67268313e-02 1.18992054e-01 4.66442197e-01
 4.07302720e-01 2.93938584e-01 7.96595916e-01 8.70565882e-01
 2.81151137e-04 3.08623297e-01 2.81884645e-01 7.90964695e-01
 1.18525848e-01 4.21424554e-01 2.66777326e-01 4.29893814e-01
 4.90178392e-01 1.65916494e-01 9.78464213e-01 6.74284262e-01
 1.56190165e-01 3.20355378e-01 5.45918286e-01 4.48517348e-02
 6.74442300e-01 4.40862635e-01 5.87678773e-01 2.97840698e-01
 5.51868670e-01 7.72230507e-01]
Skill_factor: 0

In [ ]:
A = np.array([1, 2, 4, 3]) 
A[np.array([1, 2])]

array([2, 4])

In [ ]:
# a = pop[0].ls_inds[np.random.choice(np.arange(len(pop[0])), size= (3,))]
# NOTE 

b = np.random.choice(len(pop[0]), size= (3,))
array = np.zeros(shape= (3,), dtype= int) + 1 
pop[0].ls_inds[array.astype(int)]

TypeError: only integer scalar arrays can be converted to a scalar index

In [ ]:
print(ind)

[0.63520159 0.87702451 0.90260758 0.72828481 0.02223801 0.62329283
 0.68277928 0.14066146 0.11995038 0.92090546 0.26905381 0.77802192
 0.65639471 0.72438421 0.16584222 0.52941801 0.94608122 0.73552676
 0.53833064 0.2072887  0.83442857 0.89316712 0.11187493 0.22481655
 0.86983241 0.87212036 0.81380758 0.62331769 0.08614856 0.16639344
 0.15348774 0.29431833 0.55893436 0.75205401 0.59515297 0.71665767
 0.15940989 0.30772163 0.1749303  0.61392957 0.54993999 0.35857483
 0.07993074 0.37683643 0.66338496 0.27717463 0.88193635 0.31665742
 0.47988058 0.8148288 ]


In [ ]:
a = pop.__getRandomInds__(size = 3)

TypeError: only integer scalar arrays can be converted to a scalar index

In [ ]:
print(ind3.fcost)

39.18849359751992


In [ ]:
print(ind3.skill_factor)

3


In [ ]:
print([len(pop[i]) for i in range(10)])

[10, 10, 10, 10, 10, 10, 10, 10, 10, 10]
10
10


In [ ]:
print(len(pop))

100
